version: "3"
services:
  web:
    image: webserver
    links:
      - influxdb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8888:5000"
    networks:
      - webnet
    volumes:
      - source-content:/var/run/web
    depends_on:
      - "influxdb"
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    networks:
      - webnet
  gcc-builder:
      image: gccbuilder
      volumes:
        - source-content:/var/run/poll_src
        - result-content:/var/run/poll_res
  parser:
      image: parser
      volumes:
        - result-content:/var/run/results
      networks:
        - webnet
      depends_on:
        - "influxdb"

networks:
  webnet:
volumes:
  source-content:
  result-content:
