version: "3"
services:
  web:
    image: razvan12/webserver:example4
    links:
      - influxdb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8888:5000"
    networks:
      - webnet
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    networks:
      - webnet
networks:
  webnet:
