version: "3"
services:
  web:
    image: razvan12/webserver:example
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8888:5000"
    networks:
      - webnet
    volumes:
      - source-content-gcc:/var/run/web/gcc
      - source-content-clang:/var/run/web/clang
    depends_on:
      - "influxdb"
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    networks:
      - webnet
  gcc-builder:
      image: razvan12/gccbuilder:example
      volumes:
        - source-content-gcc:/var/run/poll_src
        - result-content:/var/run/poll_res
  clang-builder:
    image: razvan12/clangbuilder:example
    volumes:
      - source-content-clang:/var/run/poll_src
      - result-content:/var/run/poll_res
  parser:
      image: razvan12/parser:example
      volumes:
        - result-content:/var/run/results
      networks:
        - webnet
      depends_on:
        - "influxdb"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    # Keep dashboards when stop/remove
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - webnet

networks:
  webnet:
volumes:
  source-content-gcc:
  source-content-clang:
  result-content:
  grafana:
