import os
from influxdb import InfluxDBClient

WORK_DIR = '/home/razvan/BuildWebServer/parser/test'
LOG_FILE = '/var/log/parser'

def poll_results():
    """
    Search for result files and inspect them
    """
    res_list = os.listdir(WORK_DIR)
    print ("List is : %s" % res_list)
    # Iterate through all files
    for f_name in res_list:
        # Check extension
        print ("File = %s" % f_name)
        if os.path.splitext(f_name)[1] == '.result':
            hashid = os.path.splitext(f_name)[0]
            parse_results("%s/%s" % (WORK_DIR, f_name))
        else:
            # Error
            os.remove("%s/%s" %(WORK_DIR, f_name))
            with open(LOG_FILE, "a") as log:
                log.write("[ERROR]: Unknown type %s\n" % f_name)


def parse_results(filename):
    """
    This function will parse the compilation files generated by builders.
    At the end, results will be posted to InfluxDB
    """
    print ("parse_results called for file = %s" % filename)
    with open(filename, "r") as file:
        content = file.readlines()
        print ("Content %s" % content)
        for line in content:
            print ("line = %s" % line)

if __name__ == "__main__":
    poll_results()