#!/bin/bash

case "$1" in
start)
	# Create log directory
	mkdir /var/log/poll
	echo "mkdir /var/log/poll exit with code $?"
	# Create sources directory
	mkdir /var/run/poll
	echo "mkdir /var/run/poll exit with code $?"
	ls -al /usr/local/bin
	ps aux
	nohup /usr/local/bin/poll.sh /var/run/poll py 5
	echo $!>/var/run/poll.pid
	ps aux
	ps aux
	ps aux
	ps aux
	ps aux
	echo "Error after staring script = $?"
	;;
stop)
	kill $(cat /var/run/poll.pid)
	rm /var/run/poll.pid
	rm -rf /var/log/poll
	rm -rf /var/run/poll
	;;
restart)
	$0 stop
	$0 start
	;;
status)
	if [ -e /var/run/poll.pid ]; then
		pid=$(cat /var/run/poll.pid)
		echo "Poll service is running... PID = $pid"
	else
		echo "Poll service is not running"
		exit 1
	fi
	;;
*)
	echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
